[package]
name = "cminus"
version = "0.1.0"
authors = ["chirsz <chirsz@foxmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.17"

[dependencies]
lalrpop-util = "0.17"
regex = "0.2"
pest = "2.0"
pest_derive = "2.0"
